name: CI
on: 
  push:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
      
    steps:
      - name: Obtendo o código fonte
        uses: actions/checkout@v4.1.2
        
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
        
      - name: Docker build 
        uses: docker/build-push-action@v5.3.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: false
          tags: |
            fabricioveronez/conversao-temperatura-aula:v${{ github.run_number }}
            fabricioveronez/conversao-temperatura-aula:latest
